### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by vynnus** [FrenetGatewaydeFretes/frenet_opencart#3]
O módulo parou de funcionar de repente.
E agora retorna uma série de erros.

![error-frenet](https://cloud.githubusercontent.com/assets/4274662/17840881/67344ed4-67e7-11e6-80d2-f5f83dff5243.png)

**Comment by rafaelmancini** [comment]
Olá @vynnus,
Você poderia por favor enviar esta ocorrência para a Central de Ajuda do Frenet (https://frenet.zendesk.com/)

**Comment by vynnus** [comment]
ok, feito
